project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "CMMR Developer News"
  site-url: "https://cmmr.github.io"

  # Navigation Bar
  navbar:
    right:
      - icon: github
        href: https://github.com/cmmr
      - icon: rss
        href: index.xml

  # Organization Sidebar
  sidebar:
    style: "floating"
    contents:
      - section: "Public Repositories"
        contents:
          - text: "EsViritu (Viral Discovery)"
            href: https://github.com/cmmr/EsViritu
          - text: "virmap (Taxonomic Mapping)"
            href: https://github.com/cmmr/virmap
          - text: "Marker-MAGu (Metagenomic Profiling)"
            href: https://github.com/cmmr/Marker-MAGu
          - text: "rbiom (Microbiome Analysis)"
            href: https://cmmr.github.io/rbiom
          - text: "ecodive (Ecological Diversity)"
            href: https://cmmr.github.io/ecodive
          - text: "h5lite (HDF5 Interface)"
            href: https://cmmr.github.io/h5lite
          - text: "fillpattern (ggplot2 Pattern Fills)"
            href: https://github.com/cmmr/fillpattern
          - text: "interprocess (Multiprocess Control)"
            href: https://github.com/cmmr/interprocess

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

