project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "CMMR Developer News"
  site-url: "https://cmmr.github.io/"
  navbar:
    right:
      - icon: github
        href: https://github.com/cmmr
      - icon: rss
        href: index.xml

listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: true
  feed: true

format:
  html:
    theme:
      light: cosmo
      dark: darkly



