project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "CMMR Developer News"
  site-url: "https://cmmr.github.io"

  # Navigation Bar
  navbar:
    right:
      - icon: github
        href: https://github.com/cmmr
      - icon: rss
        href: index.xml

  # Organization Sidebar
  sidebar:
    style: "floating"
    contents:
      - section: "Public Repositories"
        contents:
          - text: "**EsViritu**<br><small class='repo-desc'>Viral Discovery</small>"
            href: https://github.com/cmmr/EsViritu
          - text: "**virmap**<br><small class='repo-desc'>Taxonomic Mapping</small>"
            href: https://github.com/cmmr/virmap
          - text: "**Marker-MAGu**<br><small class='repo-desc'>Metagenomic Profiling</small>"
            href: https://github.com/cmmr/Marker-MAGu
          - text: "**rbiom**<br><small class='repo-desc'>Microbiome Analysis</small>"
            href: https://cmmr.github.io/rbiom
          - text: "**ecodive**<br><small class='repo-desc'>Ecological Diversity</small>"
            href: https://cmmr.github.io/ecodive
          - text: "**h5lite**<br><small class='repo-desc'>HDF5 Interface</small>"
            href: https://cmmr.github.io/h5lite
          - text: "**fillpattern**<br><small class='repo-desc'>ggplot2 Pattern Fills</small>"
            href: https://github.com/cmmr/fillpattern
          - text: "**interprocess**<br><small class='repo-desc'>Multiprocess Control</small>"
            href: https://github.com/cmmr/interprocess

  # Footer with Official Info
  page-footer:
    background: light
    left: "Â© 2026 CMMR / Baylor College of Medicine"
    right:
      - text: "Alkek Center for Metagenomics & Microbiome Research"
        href: https://www.bcm.edu/research/research-centers/alkek-center-for-metagenomics-and-microbiome-research

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
