name: Render and Publish
on:
  workflow_dispatch:
  push:
    branches: master
    paths:
      - 'posts/**'
      - '_quarto.yml'
      - '.github/workflows/publish.yaml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # Fetch all history so we can push back to main
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R Packages
        run: |
          install.packages(c("rmarkdown", "knitr"))
        shell: Rscript {0}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Frozen Results back to Main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _freeze
          git commit -m "Add frozen results from latest render [skip ci]" || echo "No changes to commit"
          git push origin main
